// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelourEssence.Infraestructure.Data;

#nullable disable

namespace VelourEssence.Infraestructure.Migrations
{
    [DbContext(typeof(VelourEssenceContext))]
    [Migration("20250821205624_AddPasswordResetTokenToUsuario")]
    partial class AddPasswordResetTokenToUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductoEtiqueta", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdEtiqueta")
                        .HasColumnType("int");

                    b.HasKey("IdProducto", "IdEtiqueta")
                        .HasName("PK__Producto__2C8C8F620171AAD3");

                    b.HasIndex("IdEtiqueta");

                    b.ToTable("ProductoEtiqueta");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito")
                        .HasName("PK__Carrito__8B4A618C45A7EB76");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.CarritoProducto", b =>
                {
                    b.Property<int>("IdCarrito")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito", "IdProducto")
                        .HasName("PK__CarritoP__9BD2E8AD71965EB4");

                    b.HasIndex("IdProducto");

                    b.ToTable("CarritoProducto");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.CarritoProductoPersonalizado", b =>
                {
                    b.Property<int>("IdCarrito")
                        .HasColumnType("int");

                    b.Property<int>("IdProductoPersonalizado")
                        .HasColumnType("int");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito", "IdProductoPersonalizado")
                        .HasName("PK__CarritoP__AFC5164E09C559CC");

                    b.HasIndex("IdProductoPersonalizado");

                    b.ToTable("CarritoProductoPersonalizado");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__A3C02A10ED283C6D");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.CriterioPersonalizacion", b =>
                {
                    b.Property<int>("IdCriterio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCriterio"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Obligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Lista");

                    b.HasKey("IdCriterio");

                    b.HasIndex("ProductoId");

                    b.ToTable("CriterioPersonalizacion", (string)null);
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.EstadoPedido", b =>
                {
                    b.Property<int>("IdEstadoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoPedido"));

                    b.Property<string>("NombreEstado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstadoPedido")
                        .HasName("PK__EstadoPe__86B98371275F5822");

                    b.ToTable("EstadoPedido");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Etiqueta", b =>
                {
                    b.Property<int>("IdEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtiqueta"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEtiqueta")
                        .HasName("PK__Etiqueta__5041D723CE1AB381");

                    b.ToTable("Etiqueta");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.ImagenProducto", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImagen")
                        .HasName("PK__ImagenPr__B42D8F2AD26D1EBA");

                    b.HasIndex("IdProducto");

                    b.ToTable("ImagenProducto");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.OpcionPersonalizacion", b =>
                {
                    b.Property<int>("IdOpcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOpcion"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCriterio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdOpcion");

                    b.HasIndex("IdCriterio");

                    b.ToTable("OpcionPersonalizacion", (string)null);
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FechaExpiracion")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoRecibido")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NombreTitular")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroTarjetaEnmascarado")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Vuelto")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPago")
                        .HasName("PK__Pago__FC851A3A7E5A9654");

                    b.HasIndex("IdPedido");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdEstadoPedido")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal?>("Impuesto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPedido")
                        .HasName("PK__Pedido__9D335DC3E899E9E9");

                    b.HasIndex("IdEstadoPedido");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.PedidoProducto", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPedido", "IdProducto")
                        .HasName("PK__PedidoPr__8DABD4E271B8A565");

                    b.HasIndex("IdProducto");

                    b.ToTable("PedidoProducto");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Concentracion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__098892105564441A");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.ProductoPersonalizado", b =>
                {
                    b.Property<int>("IdProductoPersonalizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoPersonalizado"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdProductoBase")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdProductoPersonalizado")
                        .HasName("PK__Producto__48F77C23E95940B2");

                    b.HasIndex("IdProductoBase");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ProductoPersonalizado");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.ProductoPersonalizadoDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<DateTime>("FechaSeleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCriterio")
                        .HasColumnType("int");

                    b.Property<int>("IdOpcion")
                        .HasColumnType("int");

                    b.Property<int>("IdProductoPersonalizado")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioOpcion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ValorPersonalizado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdCriterio");

                    b.HasIndex("IdOpcion");

                    b.HasIndex("IdProductoPersonalizado");

                    b.ToTable("ProductoPersonalizadoDetalles");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Promocion", b =>
                {
                    b.Property<int>("IdPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromocion"));

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPromocion")
                        .HasName("PK__Promocio__35F6C2A580C8FF4A");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProducto");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Reseña", b =>
                {
                    b.Property<int>("IdReseña")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReseña"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("Valoracion")
                        .HasColumnType("int");

                    b.HasKey("IdReseña")
                        .HasName("PK__Reseña__A5376EA622AC1C96");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdUsuario", "IdProducto" }, "UQ__Reseña__4BFD36B779AA405A")
                        .IsUnique()
                        .HasFilter("[IdUsuario] IS NOT NULL AND [IdProducto] IS NOT NULL");

                    b.ToTable("Reseña");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__2A49584CFE50E5F6");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimoInicioSesion")
                        .HasColumnType("datetime");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF976AA1F6F1");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuario__60695A1915B40EEE")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProductoEtiqueta", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("IdEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProductoE__IdEti__398D8EEE");

                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProductoE__IdPro__38996AB5");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Carrito", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Carrito")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Carrito__IdUsuar__3C69FB99");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.CarritoProducto", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Carrito", "IdCarritoNavigation")
                        .WithMany("CarritoProducto")
                        .HasForeignKey("IdCarrito")
                        .IsRequired()
                        .HasConstraintName("FK__CarritoPr__IdCar__412EB0B6");

                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("CarritoProducto")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__CarritoPr__IdPro__4222D4EF");

                    b.Navigation("IdCarritoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.CarritoProductoPersonalizado", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Carrito", "IdCarritoNavigation")
                        .WithMany("CarritoProductoPersonalizado")
                        .HasForeignKey("IdCarrito")
                        .IsRequired()
                        .HasConstraintName("FK__CarritoPr__IdCar__44FF419A");

                    b.HasOne("VelourEssence.Infraestructure.Models.ProductoPersonalizado", "IdProductoPersonalizadoNavigation")
                        .WithMany("CarritoProductoPersonalizado")
                        .HasForeignKey("IdProductoPersonalizado")
                        .IsRequired()
                        .HasConstraintName("FK__CarritoPr__IdPro__45F365D3");

                    b.Navigation("IdCarritoNavigation");

                    b.Navigation("IdProductoPersonalizadoNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.CriterioPersonalizacion", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.ImagenProducto", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("ImagenProducto")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__ImagenPro__IdPro__2F10007B");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.OpcionPersonalizacion", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.CriterioPersonalizacion", "IdCriterioNavigation")
                        .WithMany("Opciones")
                        .HasForeignKey("IdCriterio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCriterioNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Pago", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK__Pago__IdPedido__5534567C");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Pedido", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.EstadoPedido", "IdEstadoPedidoNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("IdEstadoPedido")
                        .HasConstraintName("FK__Pedido__IdEstado__4CA06362");

                    b.HasOne("VelourEssence.Infraestructure.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Pedido__IdUsuari__4AB81AF0");

                    b.Navigation("IdEstadoPedidoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.PedidoProducto", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("PedidoProducto")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK__PedidoPro__IdPed__4F7CD00D");

                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("PedidoProducto")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__PedidoPro__IdPro__5070F446");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Producto", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Producto__IdCate__2C3393D0");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.ProductoPersonalizado", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", "BaseProducto")
                        .WithMany("ProductoPersonalizado")
                        .HasForeignKey("IdProductoBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProductoP__BaseP__32E0915F");

                    b.HasOne("VelourEssence.Infraestructure.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("ProductoPersonalizado")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__ProductoP__IdUsu__31EC6D26");

                    b.Navigation("BaseProducto");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.ProductoPersonalizadoDetalle", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.CriterioPersonalizacion", "IdCriterioNavigation")
                        .WithMany()
                        .HasForeignKey("IdCriterio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VelourEssence.Infraestructure.Models.OpcionPersonalizacion", "IdOpcionNavigation")
                        .WithMany("ProductoPersonalizadoDetalles")
                        .HasForeignKey("IdOpcion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VelourEssence.Infraestructure.Models.ProductoPersonalizado", "IdProductoPersonalizadoNavigation")
                        .WithMany("ProductoPersonalizadoDetalles")
                        .HasForeignKey("IdProductoPersonalizado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCriterioNavigation");

                    b.Navigation("IdOpcionNavigation");

                    b.Navigation("IdProductoPersonalizadoNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Promocion", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Promocion")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK_Promocion_Categoria");

                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("Promocion")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK_Promocion_Producto");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Reseña", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("Reseña")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Reseña__IdProduc__5535A963");

                    b.HasOne("VelourEssence.Infraestructure.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reseña")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Reseña__IdUsuari__5441852A");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Usuario", b =>
                {
                    b.HasOne("VelourEssence.Infraestructure.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuario__IdRol__276EDEB3");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Carrito", b =>
                {
                    b.Navigation("CarritoProducto");

                    b.Navigation("CarritoProductoPersonalizado");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Categoria", b =>
                {
                    b.Navigation("Producto");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.CriterioPersonalizacion", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.EstadoPedido", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.OpcionPersonalizacion", b =>
                {
                    b.Navigation("ProductoPersonalizadoDetalles");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Pedido", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("PedidoProducto");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Producto", b =>
                {
                    b.Navigation("CarritoProducto");

                    b.Navigation("ImagenProducto");

                    b.Navigation("PedidoProducto");

                    b.Navigation("ProductoPersonalizado");

                    b.Navigation("Promocion");

                    b.Navigation("Reseña");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.ProductoPersonalizado", b =>
                {
                    b.Navigation("CarritoProductoPersonalizado");

                    b.Navigation("ProductoPersonalizadoDetalles");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Rol", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VelourEssence.Infraestructure.Models.Usuario", b =>
                {
                    b.Navigation("Carrito");

                    b.Navigation("Pedido");

                    b.Navigation("ProductoPersonalizado");

                    b.Navigation("Reseña");
                });
#pragma warning restore 612, 618
        }
    }
}
